### ISSUE TITLE
Data link not working?

### ISSUE THREAD

**Issue by BunsenFeng** [michaelmilleryoder/hegemonic_hate#1]
Thank you for this super wonderful work! It is a great contribution to hate speech detection research and adjacent communities. I wonder if you could update the dataset link so that we can download it. We will definitely cite your wonderful work. Thanks in advance! :)

**Comment by michaelmilleryoder** [comment]
Hi and thanks! What are you seeing when you click on the data link (https://osf.io/53tfs/)? It should take you to an OSF page with the data (that's what I see), but maybe there's something going on where it's not publicly available.

**Comment by BunsenFeng** [comment]
Oh, it seems totally fine now. Yesterday when I clicked the link it says "503 bad gateway" or something. Thank you so much!

**Comment by michaelmilleryoder** [comment]
Sounds good! I think I saw a message on OSF's site about some server issues, so that might have been it.

**Comment by BunsenFeng** [comment]
Hi, thank you for your work! I downloaded the 3 JSON files at https://osf.io/53tfs/. There are five fields for each example, but is there a hate/non-hate label for these examples available somewhere, or did I miss it?

**Comment by michaelmilleryoder** [comment]
I forgot to save out that all-important field! The files are updated now to include it. Thanks for catching that! Just let me know if you still don't see it or if there are any other issues.

**Comment by BunsenFeng** [comment]
It is working right now. Thank you for your quick response!
